platform :ios, '12.0'

target 'ironsource' do
  use_frameworks!

  # Pods for ironsource
  pod 'IronSourceAdMobAdapter','4.3.47.1'
  pod 'IronSourceAppLovinAdapter','4.3.40.4'
  pod 'IronSourceAPSAdapter','4.3.8.3'
  pod 'IronSourceBidMachineAdapter','4.3.3.0'
  pod 'IronSourceFacebookAdapter','4.3.43.1'
  pod 'IronSourceFyberAdapter','4.3.31.2'
  pod 'IronSourceMintegralAdapter', '4.3.18.1'
  pod 'IronSourceSDK','7.5.1.0'
  pod 'IronSourceUnityAdsAdapter','4.3.33.1'
  pod 'IronSourceVungleAdapter','4.3.29.1'
  pod 'IronSourceTapjoyAdapter','4.1.25.4'
end
