# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ironsource' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ironsource
  pod 'IronSourceSDK','7.2.6.0'
  pod 'IronSourceAdColonyAdapter','4.3.15.3'
  pod 'IronSourceAdMobAdapter','4.3.39.0'
  pod 'IronSourceAppLovinAdapter','4.3.37.0'
  pod 'IronSourceChartboostAdapter','4.3.12.3'
  pod 'IronSourceFacebookAdapter','4.3.38.3'
  pod 'IronSourcePangleAdapter','4.3.17.1'
  pod 'IronSourceTapjoyAdapter','4.1.23.0'
  pod 'IronSourceUnityAdsAdapter','4.3.25.1'
  pod 'IronSourceVungleAdapter','4.3.23.1'
  pod 'IronSourceMintegralAdapter', '4.3.11.1'
end
