# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ironsource' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ironsource
  pod 'IronSourceSDK','7.2.4.0'
  pod 'IronSourceAdColonyAdapter','4.3.14.3'
  pod 'IronSourceAdMobAdapter','4.3.35.0'
  pod 'IronSourceAppLovinAdapter','4.3.34.1'
  pod 'IronSourceChartboostAdapter','4.3.11.0'
  pod 'IronSourceFacebookAdapter','4.3.37.0'
  pod 'IronSourcePangleAdapter','4.3.16.1'
  pod 'IronSourceTapjoyAdapter','4.1.21.1'
  pod 'IronSourceUnityAdsAdapter','4.3.23.1'
  pod 'IronSourceVungleAdapter','4.3.22.1'
end
